name: Elixir CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step: Check out the code.
      - name: Checkout code
        uses: actions/checkout@v3

      # Step: Setup Elixir + Erlang image as the base.
      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: "1.14.5" # Define the elixir version [required]
          otp-version: "25.0" # Define the OTP version [required]
      - name: Install Dependencies
        run: mix deps.get
      - name: Run Tests
        env:
          PIN_TEST_API_KEY: ${{secrets.PIN_TEST_API_KEY}}
        run: mix test
